services:
  meetingservice:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GPR_USER: ${GPR_USER}
        GPR_KEY: ${GPR_KEY}
    container_name: pagely-meetingservice
    ports:
      - "19011:19011"
    environment:
      SPRING_PROFILES_ACTIVE: dev

      DB_HOST: host.docker.internal
      DB_PORT: "5432"
      MEETING_DB_NAME: pagely_meeting
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      KAFKA_EXTERNAL_HOST: host.docker.internal
      KAFKA_EXTERNAL_PORT: "9092"

      EUREKA_SERVER_URL: http://localhost:8000/eureka/
      BOOK_SERVICE_URL: http://book-service:8080

      EUREKA_CLIENT_ENABLED: "false"
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
    depends_on:
      book-service:
        condition: service_healthy

  book-service:
    image: wiremock/wiremock:latest
    container_name: pagely-book-mock
    ports:
      - "19051:8080"
    command:
      - "--verbose"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/__admin || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 10

  prometheus:
    image: prom/prometheus:latest
    container_name: pagely-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      meetingservice:
        condition: service_started

  grafana:
    image: grafana/grafana:latest
    container_name: pagely-grafana
    ports:
      - "3000:3000"
    depends_on:
      prometheus:
        condition: service_started

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: pagely-zipkin
    ports:
      - "9411:9411"
