eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:true}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY:true}
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8000/eureka/}

book-service:
  url: ${BOOK_SERVICE_URL}

logging:
  level:
    com.pagely.meetingservice: info

management:
  endpoint:
    health:
      show-details: never
